# Example of rule configuration file

# ---
# - name: A
#   url: a.com.br/splits/publish
#   claims:
#   - host: origin.a.com.br
#     path: /ab
#     method: PUT
#   - path: /a

# - name: B
#   url: b.com.br/splits
#   timeout: 1
#   claims:
#   - path: /b
#     method: POST
#     headers:

# ---
# - name: A
#   url: https://www.stone.com.br
#   claims:
#   - host: 127.0.0.1:28080
#     path: /ab

---
- name: Example
  url: https://api.github.com
  claims:
  - host: 127.0.0.1:8080